pipeline {
    agent {
        node {
            label 'slave-dev'
        }
    }
    stages { 
        stage('slack-notification') {
            steps {
                slackSend channel: 'devops',
                    color: '439FE0',
                    message: "started ${JOB_NAME} ${BUILD_NUMBER} (<${BUILD_URL}|Open>)",
                    teamDomain: 'raghava-world',
                    tokenCredentialId: 'slack3',
                    username: 'jenkins'
            }
        }
        stage('scanning-backend') {
            steps {
               sh 'cd api && docker run --rm -e SONAR_HOST_URL="http://34.201.119.240:9000" -e SONAR_SCANNER_OPTS="-Dsonar.projectKey=lms-be" -e SONAR_TOKEN="sqp_cc2952fc7aabc82d2506e818d3f1c7ae762f910a" -v ".:/usr/src" sonarsource/sonar-scanner-cli'
          }
        }
        stage('Approval') {
            steps {
                emailext subject: "Deployment Approval for lms service",
                    body: "<a href='${JENKINS_URL}/job/${JOB_NAME}/${BUILD_NUMBER}/input'>click to approve</a>",
                    to: 'machirajuraghavarao@gmail.com',
                    mimeType: 'text/html',
                    attachLog: true
                script {
                    def Delay = input id: 'Deploy',
                        message: sh(script: '''echo "You are DEPLOYING -->$deployBranch<-- IN PRODUCTION"''', returnStdout: true).trim(),
                        submitter: 'userID1, userID2',
                        parameters: [
                            [$class: 'ChoiceParameterDefinition',
                                choices: ['no', 'yes'].join('\n'),
                                name: 'input',
                                description: 'Please Select "YES" to Build or "NO" to Abort']
                        ]
                    echo "The answer is: ${Delay}"
                    if ("${Delay}" == "yes") {
                        sh '''echo "Deploying in prod"'''
                    } else {
                        sh """
                        echo "exiting not production ready branch"
                        exit 1
                        """
                    }
                }
            }
        } 
        stage('install nodejs') {
            steps {
                sh 'curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash - &&\
                    sudo apt-get install -y nodejs'
            }
        }
        stage('connecting to backend') {
            steps {
                sh 'pwd'
                sh 'cd api/'
                sh 'pwd'
                sh 'npm install'
                sh 'pwd'
                sh'sudo npx prisma db push'
                
            }
        }
        stage('build') {
            steps {
                sh 'npm run build'
                sh 'sudo npm install -g pm2'
                sh 'pm2 start build/index.js'
            }
        }
    }
}
